services:
  web:
    build:
      dockerfile: DockerfileApache2
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        SERVICE: web
    container_name: web
    working_dir: /project/
    volumes:
      - type: bind
        source: ./web/htdocs
        target: /project/htdocs
      - type: bind
        source: ./web/cgi-bin
        target: /project/cgi-bin
    ports:
      - 80:80
  app:
    build:
      dockerfile: DockerfileApache2
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        SERVICE: app
    container_name: app
    working_dir: /project/
    volumes:
      - type: bind
        source: ./app/htdocs
        target: /project/htdocs
      - type: bind
        source: ./app/cgi-bin
        target: /project/cgi-bin
  api:
    build:
      dockerfile: DockerfileApache2
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        SERVICE: api
    container_name: api
    working_dir: /project/
    volumes:
      - type: bind
        source: ./api/htdocs
        target: /project/htdocs
      - type: bind
        source: ./api/cgi-bin
        target: /project/cgi-bin
  script:
    build:
      dockerfile: DockerfileReact
    container_name: script
    working_dir: /project/
    volumes:
      - type: bind
        source: ./script
        target: /project
    entrypoint: sh -c "cd /project/front/ && npm install && npm start"
